-- MySQL Script generated by MySQL Workbench
-- 07/04/15 09:49:58
-- Model: Minerva    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema minerva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema minerva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `minerva` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `minerva` ;

-- -----------------------------------------------------
-- Table `minerva`.`n_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_genero` (
  `id_genero` INT NOT NULL AUTO_INCREMENT,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_pais` (
  `id_pais` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_tipo_sangre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_tipo_sangre` (
  `id_tipo_sangre` INT NOT NULL AUTO_INCREMENT,
  `tipo_sangre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_sangre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_tipo_identificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_tipo_identificacion` (
  `id_tipo_identificacion` INT NOT NULL AUTO_INCREMENT,
  `n_tipo_identificacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_identificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `primer_nombre` VARCHAR(100) NOT NULL,
  `segundo_nombre` VARCHAR(100) NULL,
  `primer_apellido` VARCHAR(100) NOT NULL,
  `segundo_apellido` VARCHAR(100) NULL,
  `identificacion` VARCHAR(25) NOT NULL,
  `fecha_nacimiento` DATE NULL,
  `direccion` VARCHAR(200) NULL,
  `email` VARCHAR(45) NULL,
  `telefono1` VARCHAR(45) NULL,
  `telefono2` VARCHAR(45) NULL,
  `residencia` TINYINT(1) NOT NULL,
  `foto` BLOB NULL,
  `id_genero` INT NOT NULL,
  `id_pais` INT NOT NULL,
  `id_tipo_sangre` INT NOT NULL,
  `id_tipo_identificacion` INT NOT NULL,
  PRIMARY KEY (`id_persona`),
  INDEX `fk_persona_n_genero_idx` (`id_genero` ASC),
  INDEX `fk_persona_n_pais1_idx` (`id_pais` ASC),
  INDEX `fk_persona_n_tipo_sangre1_idx` (`id_tipo_sangre` ASC),
  INDEX `fk_persona_n_tipo_identificacion1_idx` (`id_tipo_identificacion` ASC),
  CONSTRAINT `fk_persona_n_genero`
    FOREIGN KEY (`id_genero`)
    REFERENCES `minerva`.`n_genero` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_n_pais1`
    FOREIGN KEY (`id_pais`)
    REFERENCES `minerva`.`n_pais` (`id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_n_tipo_sangre1`
    FOREIGN KEY (`id_tipo_sangre`)
    REFERENCES `minerva`.`n_tipo_sangre` (`id_tipo_sangre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_n_tipo_identificacion1`
    FOREIGN KEY (`id_tipo_identificacion`)
    REFERENCES `minerva`.`n_tipo_identificacion` (`id_tipo_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  `id_persona` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC),
  INDEX `fk_usuario_persona1_idx` (`id_persona` ASC),
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `minerva`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_inst_educativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_inst_educativa` (
  `id_inst_educativa` INT NOT NULL AUTO_INCREMENT,
  `inst_educativa` VARCHAR(45) NOT NULL,
  `id_pais` INT NOT NULL,
  PRIMARY KEY (`id_inst_educativa`),
  INDEX `fk_n_titulo_n_pais1_idx` (`id_pais` ASC),
  CONSTRAINT `fk_n_titulo_n_pais1`
    FOREIGN KEY (`id_pais`)
    REFERENCES `minerva`.`n_pais` (`id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_sist_salario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_sist_salario` (
  `id_sist_salario` INT NOT NULL AUTO_INCREMENT,
  `sist_salario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sist_salario`),
  UNIQUE INDEX `sist_salario_UNIQUE` (`sist_salario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_grupo_gastos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_grupo_gastos` (
  `id_grupo_gastos` INT NOT NULL AUTO_INCREMENT,
  `grupo_gastos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_grupo_gastos`),
  UNIQUE INDEX `grupo_gastos_UNIQUE` (`grupo_gastos` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_tipo_contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_tipo_contrato` (
  `id_tipo_contrato` INT NOT NULL AUTO_INCREMENT,
  `tipo_contrato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_contrato`),
  UNIQUE INDEX `tipo_contrato_UNIQUE` (`tipo_contrato` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_tipo_cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_tipo_cuenta` (
  `id_tipo_cuenta` INT NOT NULL AUTO_INCREMENT,
  `tipo_cuenta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_cuenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_seccion` (
  `id_seccion` INT NOT NULL AUTO_INCREMENT,
  `seccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_seccion`),
  UNIQUE INDEX `seccion_UNIQUE` (`seccion` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_estado_civil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_estado_civil` (
  `id_estado_civil` INT NOT NULL AUTO_INCREMENT,
  `estado_civil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado_civil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_titulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_titulo` (
  `id_titulo` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_titulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_dpto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_dpto` (
  `id_dpto` INT NOT NULL AUTO_INCREMENT,
  `dpto` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_dpto`),
  UNIQUE INDEX `motivo_baja_UNIQUE` (`dpto` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_responsabilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_responsabilidad` (
  `id_responsabilidad` INT NOT NULL AUTO_INCREMENT,
  `responsabilidad` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_responsabilidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_cargo` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NOT NULL,
  `nivel` VARCHAR(50) NOT NULL,
  `area` VARCHAR(50) NOT NULL,
  `nombre_cargo` VARCHAR(50) NOT NULL,
  `nombre_cargo_jefe` VARCHAR(50) NOT NULL,
  `ubic_geo` VARCHAR(50) NOT NULL,
  `mision` VARCHAR(250) NOT NULL,
  `no_personas_a_cargo` INT NOT NULL,
  `magnitudes_econ` FLOAT NOT NULL,
  `otras_magnitudes` FLOAT NOT NULL,
  `autorizaciones` VARCHAR(500) NULL,
  `relaciones_int` VARCHAR(250) NULL,
  `relaciones_ext` VARCHAR(250) NULL,
  `debe_saber` VARCHAR(1000) NOT NULL,
  `experiencia_previa` INT NOT NULL,
  `periodo_entrenamiento` INT NOT NULL,
  `id_responsabilidad` INT NOT NULL,
  PRIMARY KEY (`id_cargo`),
  INDEX `fk_perfil_cargo_n_responsabilidad1_idx` (`id_responsabilidad` ASC),
  CONSTRAINT `fk_perfil_cargo_n_responsabilidad1`
    FOREIGN KEY (`id_responsabilidad`)
    REFERENCES `minerva`.`n_responsabilidad` (`id_responsabilidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `numero_cuenta` FLOAT NULL,
  `email_inst` VARCHAR(45) NULL,
  `telefono_inst` VARCHAR(45) NULL,
  `id_biometrico` INT NULL,
  `id_persona` INT NOT NULL,
  `id_inst_educativa` INT NOT NULL,
  `id_sist_salario` INT NOT NULL,
  `id_grupo_gastos` INT NOT NULL,
  `id_tipo_contrato` INT NOT NULL,
  `id_tipo_cuenta` INT NOT NULL,
  `id_seccion` INT NOT NULL,
  `id_dpto` INT NOT NULL,
  `id_estado_civil` INT NOT NULL,
  `id_titulo` INT NOT NULL,
  `id_cargo_jefe` INT NOT NULL,
  `baja` VARCHAR(1) NOT NULL,
  `camino_foto` BLOB NULL,
  PRIMARY KEY (`id_empleado`),
  UNIQUE INDEX `numero_cuenta_UNIQUE` (`numero_cuenta` ASC),
  INDEX `fk_empleado_n_titulo1_idx` (`id_inst_educativa` ASC),
  INDEX `fk_empleado_n_sist_salario1_idx` (`id_sist_salario` ASC),
  INDEX `fk_empleado_n_grupo_gastos1_idx` (`id_grupo_gastos` ASC),
  INDEX `fk_empleado_n_tipo_contrato1_idx` (`id_tipo_contrato` ASC),
  INDEX `fk_empleado_n_tipo_cuenta1_idx` (`id_tipo_cuenta` ASC),
  INDEX `fk_empleado_n_seccion1_idx` (`id_seccion` ASC),
  INDEX `fk_empleado_persona2_idx` (`id_persona` ASC),
  UNIQUE INDEX `id_persona_UNIQUE` (`id_persona` ASC),
  INDEX `fk_empleado_n_estado_civil1_idx` (`id_estado_civil` ASC),
  INDEX `fk_empleado_n_titulo2_idx` (`id_titulo` ASC),
  INDEX `fk_empleado_n_dpto1_idx` (`id_dpto` ASC),
  INDEX `fk_empleado_n_cargo1_idx` (`id_cargo_jefe` ASC),
  CONSTRAINT `fk_empleado_n_titulo1`
    FOREIGN KEY (`id_inst_educativa`)
    REFERENCES `minerva`.`n_inst_educativa` (`id_inst_educativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_n_sist_salario1`
    FOREIGN KEY (`id_sist_salario`)
    REFERENCES `minerva`.`n_sist_salario` (`id_sist_salario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_n_grupo_gastos1`
    FOREIGN KEY (`id_grupo_gastos`)
    REFERENCES `minerva`.`n_grupo_gastos` (`id_grupo_gastos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_n_tipo_contrato1`
    FOREIGN KEY (`id_tipo_contrato`)
    REFERENCES `minerva`.`n_tipo_contrato` (`id_tipo_contrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_n_tipo_cuenta1`
    FOREIGN KEY (`id_tipo_cuenta`)
    REFERENCES `minerva`.`n_tipo_cuenta` (`id_tipo_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_n_seccion1`
    FOREIGN KEY (`id_seccion`)
    REFERENCES `minerva`.`n_seccion` (`id_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_persona2`
    FOREIGN KEY (`id_persona`)
    REFERENCES `minerva`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_n_estado_civil1`
    FOREIGN KEY (`id_estado_civil`)
    REFERENCES `minerva`.`n_estado_civil` (`id_estado_civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_n_titulo2`
    FOREIGN KEY (`id_titulo`)
    REFERENCES `minerva`.`n_titulo` (`id_titulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_n_dpto1`
    FOREIGN KEY (`id_dpto`)
    REFERENCES `minerva`.`n_dpto` (`id_dpto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_n_cargo1`
    FOREIGN KEY (`id_cargo_jefe`)
    REFERENCES `minerva`.`n_cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_accion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_accion` (
  `id_accion` INT NOT NULL AUTO_INCREMENT,
  `accion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_accion`),
  UNIQUE INDEX `accion_UNIQUE` (`accion` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_elemento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_elemento` (
  `id_elemento` INT NOT NULL AUTO_INCREMENT,
  `elemento` VARCHAR(45) NOT NULL,
  `modulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `orden` INT NOT NULL,
  PRIMARY KEY (`id_elemento`),
  UNIQUE INDEX `pagina_UNIQUE` (`elemento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`permiso` (
  `id_permiso` INT NOT NULL AUTO_INCREMENT,
  `id_rol` INT NOT NULL,
  `id_elemento` INT NOT NULL,
  `id_accion` INT NOT NULL,
  PRIMARY KEY (`id_permiso`),
  INDEX `fk_permiso_n_rol1_idx` (`id_rol` ASC),
  INDEX `fk_permiso_n_pagina1_idx` (`id_elemento` ASC),
  INDEX `fk_permiso_n_accion1_idx` (`id_accion` ASC),
  CONSTRAINT `fk_permiso_n_rol1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `minerva`.`n_rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permiso_n_pagina1`
    FOREIGN KEY (`id_elemento`)
    REFERENCES `minerva`.`n_elemento` (`id_elemento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permiso_n_accion1`
    FOREIGN KEY (`id_accion`)
    REFERENCES `minerva`.`n_accion` (`id_accion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_criterio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_criterio` (
  `id_criterio` INT NOT NULL AUTO_INCREMENT,
  `cod_criterio` VARCHAR(10) NOT NULL,
  `criterio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_criterio`),
  UNIQUE INDEX `criterio_UNIQUE` (`criterio` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`grupo_eval`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`grupo_eval` (
  `id_grupo_eval` INT NOT NULL AUTO_INCREMENT,
  `grupo_eval` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_grupo_eval`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`cri_eval`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`cri_eval` (
  `id_cri_eval` INT NOT NULL AUTO_INCREMENT,
  `id_criterio` INT NOT NULL,
  `id_grupo_eval` INT NOT NULL,
  PRIMARY KEY (`id_cri_eval`),
  INDEX `fk_cri_eval_pond_n_criterio1_idx` (`id_criterio` ASC),
  INDEX `fk_cri_eval_pond_grupo_eval1_idx` (`id_grupo_eval` ASC),
  CONSTRAINT `fk_cri_eval_pond_n_criterio1`
    FOREIGN KEY (`id_criterio`)
    REFERENCES `minerva`.`n_criterio` (`id_criterio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cri_eval_pond_grupo_eval1`
    FOREIGN KEY (`id_grupo_eval`)
    REFERENCES `minerva`.`grupo_eval` (`id_grupo_eval`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_tipo_competencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_tipo_competencia` (
  `id_tipo_competencia` INT NOT NULL AUTO_INCREMENT,
  `tipo_competencia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_competencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_competencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_competencia` (
  `id_competencia` INT NOT NULL AUTO_INCREMENT,
  `competencia` VARCHAR(200) NOT NULL,
  `id_tipo_competencia` INT NOT NULL,
  PRIMARY KEY (`id_competencia`),
  INDEX `fk_n_competencia_n_tipo_competencia1_idx` (`id_tipo_competencia` ASC),
  CONSTRAINT `fk_n_competencia_n_tipo_competencia1`
    FOREIGN KEY (`id_tipo_competencia`)
    REFERENCES `minerva`.`n_tipo_competencia` (`id_tipo_competencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`comp_cri_eval`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`comp_cri_eval` (
  `id_comp_cri_eval` INT NOT NULL AUTO_INCREMENT,
  `id_cri_eval` INT NOT NULL,
  `id_competencia` INT NOT NULL,
  `orden` INT NOT NULL,
  PRIMARY KEY (`id_comp_cri_eval`),
  INDEX `fk_n_competencia_eval_pond1_idx` (`id_cri_eval` ASC),
  INDEX `fk_n_competencia_n_competencia1_idx` (`id_competencia` ASC),
  CONSTRAINT `fk_n_competencia_eval_pond1`
    FOREIGN KEY (`id_cri_eval`)
    REFERENCES `minerva`.`cri_eval` (`id_cri_eval`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_n_competencia_n_competencia1`
    FOREIGN KEY (`id_competencia`)
    REFERENCES `minerva`.`n_competencia` (`id_competencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_evaluacion` (
  `id_evaluacion` INT NOT NULL AUTO_INCREMENT,
  `cod_evaluacion` VARCHAR(5) NOT NULL,
  `evaluacion` VARCHAR(45) NOT NULL,
  `valor_e` INT NOT NULL,
  `exp_eval` VARCHAR(100) NOT NULL,
  `orden_e` INT NOT NULL,
  `id_grupo_eval` INT NOT NULL,
  PRIMARY KEY (`id_evaluacion`),
  INDEX `fk_n_evaluacion_grupo_eval1_idx` (`id_grupo_eval` ASC),
  CONSTRAINT `fk_n_evaluacion_grupo_eval1`
    FOREIGN KEY (`id_grupo_eval`)
    REFERENCES `minerva`.`grupo_eval` (`id_grupo_eval`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_ponderacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_ponderacion` (
  `id_ponderacion` INT NOT NULL AUTO_INCREMENT,
  `cod_ponderacion` VARCHAR(5) NOT NULL,
  `ponderacion` VARCHAR(100) NOT NULL,
  `valor_p` INT NOT NULL,
  `exp_pond` VARCHAR(200) NOT NULL,
  `orden_p` INT NOT NULL,
  PRIMARY KEY (`id_ponderacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_periodo` (
  `id_periodo` INT NOT NULL AUTO_INCREMENT,
  `fecha_ini` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `fecha_conclusion` DATE NOT NULL,
  PRIMARY KEY (`id_periodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`compromiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`compromiso` (
  `id_compromiso` INT NOT NULL AUTO_INCREMENT,
  `compromiso` VARCHAR(300) NOT NULL,
  `puntaje_a_obtener` FLOAT NOT NULL,
  `fecha` DATE NOT NULL,
  `id_competencia` INT NOT NULL,
  PRIMARY KEY (`id_compromiso`),
  INDEX `fk_compromiso_n_competencia1_idx` (`id_competencia` ASC),
  CONSTRAINT `fk_compromiso_n_competencia1`
    FOREIGN KEY (`id_competencia`)
    REFERENCES `minerva`.`n_competencia` (`id_competencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`desempeno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`desempeno` (
  `id_desempeno` INT NOT NULL AUTO_INCREMENT,
  `id_empleado` INT NOT NULL,
  `id_periodo` INT NOT NULL,
  `id_competencia` INT NOT NULL,
  `id_criterio` INT NOT NULL,
  `id_evaluacion` INT NOT NULL,
  `id_compromiso` INT NOT NULL,
  `id_cargo` INT NOT NULL,
  `id_empleado_jefe` INT NOT NULL,
  `resultado_cri` FLOAT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id_desempeno`),
  INDEX `fk_desempeño_n_periodo1_idx` (`id_periodo` ASC),
  INDEX `fk_desempeño_empleado1_idx` (`id_empleado` ASC),
  INDEX `fk_desempeño_n_criterio1_idx` (`id_criterio` ASC),
  INDEX `fk_desempeño_n_evaluacion1_idx` (`id_evaluacion` ASC),
  INDEX `fk_desempeño_n_competencia1_idx` (`id_competencia` ASC),
  INDEX `fk_desempeno_empleado1_idx` (`id_empleado_jefe` ASC),
  INDEX `fk_desempeno_n_cargo1_idx` (`id_cargo` ASC),
  INDEX `fk_desempeno_compromiso1_idx` (`id_compromiso` ASC),
  CONSTRAINT `fk_desempeño_n_periodo1`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `minerva`.`n_periodo` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_desempeño_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `minerva`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_desempeño_n_criterio1`
    FOREIGN KEY (`id_criterio`)
    REFERENCES `minerva`.`n_criterio` (`id_criterio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_desempeño_n_evaluacion1`
    FOREIGN KEY (`id_evaluacion`)
    REFERENCES `minerva`.`n_evaluacion` (`id_evaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_desempeño_n_competencia1`
    FOREIGN KEY (`id_competencia`)
    REFERENCES `minerva`.`n_competencia` (`id_competencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_desempeno_empleado1`
    FOREIGN KEY (`id_empleado_jefe`)
    REFERENCES `minerva`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_desempeno_n_cargo1`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `minerva`.`n_cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_desempeno_compromiso1`
    FOREIGN KEY (`id_compromiso`)
    REFERENCES `minerva`.`compromiso` (`id_compromiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`cargo_comp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`cargo_comp` (
  `id_cargo_comp` INT NOT NULL AUTO_INCREMENT,
  `id_competencia` INT NOT NULL,
  `id_cargo` INT NOT NULL,
  `id_ponderacion` INT NOT NULL,
  `puntaje` FLOAT NULL,
  PRIMARY KEY (`id_cargo_comp`),
  INDEX `fk_cargo_comp_n_competencia1_idx` (`id_competencia` ASC),
  INDEX `fk_cargo_comp_n_cargo1_idx` (`id_cargo` ASC),
  INDEX `fk_cargo_comp_n_ponderacion1_idx` (`id_ponderacion` ASC),
  CONSTRAINT `fk_cargo_comp_n_competencia1`
    FOREIGN KEY (`id_competencia`)
    REFERENCES `minerva`.`n_competencia` (`id_competencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cargo_comp_n_cargo1`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `minerva`.`n_cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cargo_comp_n_ponderacion1`
    FOREIGN KEY (`id_ponderacion`)
    REFERENCES `minerva`.`n_ponderacion` (`id_ponderacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`c_vacaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`c_vacaciones` (
  `id_vacaciones` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `cant_dias_x_anno` INT NOT NULL,
  `sab_dom` VARCHAR(1) NOT NULL,
  `aumento_x_anno_extra` INT NULL,
  `anno_extra_ini` INT NULL,
  `max_dias` INT NULL,
  `fecha_vigencia` DATE NOT NULL,
  PRIMARY KEY (`id_vacaciones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_grupo` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `grupo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_grupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_jornada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_jornada` (
  `id_jornada` INT NOT NULL AUTO_INCREMENT,
  `hora_ini` TIME NOT NULL,
  `hora_tardanza` TIME NOT NULL,
  `hora_sin_entrada` TIME NOT NULL,
  `hora_fin` TIME NOT NULL,
  `hora_antelacion` TIME NOT NULL,
  `hora_sin_salida` TIME NOT NULL,
  `fecha_vigencia` DATE NOT NULL,
  `pago_horas_extras` VARCHAR(1) NOT NULL,
  `id_vacaciones` INT NOT NULL,
  `id_grupo` INT NOT NULL,
  PRIMARY KEY (`id_jornada`),
  INDEX `fk_n_jornada_c_vacaciones1_idx` (`id_vacaciones` ASC),
  INDEX `fk_n_jornada_n_grupo1_idx` (`id_grupo` ASC),
  CONSTRAINT `fk_n_jornada_c_vacaciones1`
    FOREIGN KEY (`id_vacaciones`)
    REFERENCES `minerva`.`c_vacaciones` (`id_vacaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_n_jornada_n_grupo1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `minerva`.`n_grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`registro_biometrico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`registro_biometrico` (
  `id_registro_biometrico` INT NOT NULL AUTO_INCREMENT,
  `fecha_registro` DATETIME NULL,
  `validez` VARCHAR(1) NOT NULL,
  `registro_manual` VARCHAR(1) NOT NULL,
  `id_empleado` INT NOT NULL,
  PRIMARY KEY (`id_registro_biometrico`),
  INDEX `fk_registro_biometrico_empleado1_idx` (`id_empleado` ASC),
  CONSTRAINT `fk_registro_biometrico_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `minerva`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`vacaciones_ejec`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`vacaciones_ejec` (
  `id_vacaciones_ejec` INT NOT NULL AUTO_INCREMENT,
  `fecha_ini` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `disfrutadas` VARCHAR(1) NOT NULL,
  `id_empleado` INT NOT NULL,
  PRIMARY KEY (`id_vacaciones_ejec`),
  INDEX `fk_vacaciones_empleado1_idx` (`id_empleado` ASC),
  CONSTRAINT `fk_vacaciones_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `minerva`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_causa_ausencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_causa_ausencia` (
  `id_causa_ausencia` INT NOT NULL AUTO_INCREMENT,
  `causa_ausencia` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_causa_ausencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`ausencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`ausencia` (
  `id_ausencia` INT NOT NULL AUTO_INCREMENT,
  `autorizo_ini` DATETIME NOT NULL,
  `autorizo_fin` DATETIME NOT NULL,
  `fecha` DATE NOT NULL,
  `justificacion` VARCHAR(250) NULL,
  `doc_justificativo` BLOB NULL,
  `recuperable` VARCHAR(1) NOT NULL,
  `con_pago` VARCHAR(1) NOT NULL,
  `autorizado` VARCHAR(1) NOT NULL DEFAULT 0,
  `revisado` VARCHAR(1) NOT NULL DEFAULT 0,
  `id_empleado_autoriza` INT NULL,
  `id_empleado` INT NOT NULL,
  `id_causa_ausencia` INT NOT NULL,
  PRIMARY KEY (`id_ausencia`),
  INDEX `fk_permiso_empleado1_idx` (`id_empleado` ASC),
  INDEX `fk_ausencia_n_causa_ausencia1_idx` (`id_causa_ausencia` ASC),
  CONSTRAINT `fk_permiso_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `minerva`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ausencia_n_causa_ausencia1`
    FOREIGN KEY (`id_causa_ausencia`)
    REFERENCES `minerva`.`n_causa_ausencia` (`id_causa_ausencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_eventos_feriado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_eventos_feriado` (
  `id_eventos_feriado` INT NOT NULL AUTO_INCREMENT,
  `eventos_feriado` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_eventos_feriado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_feriados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_feriados` (
  `id_feriados` INT NOT NULL AUTO_INCREMENT,
  `feriado` DATE NOT NULL,
  `recuperable` VARCHAR(1) NOT NULL,
  `id_eventos_feriado` INT NOT NULL,
  PRIMARY KEY (`id_feriados`),
  INDEX `fk_n_feriados_n_eventos_feriado1_idx` (`id_eventos_feriado` ASC),
  CONSTRAINT `fk_n_feriados_n_eventos_feriado1`
    FOREIGN KEY (`id_eventos_feriado`)
    REFERENCES `minerva`.`n_eventos_feriado` (`id_eventos_feriado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`dia_recuperable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`dia_recuperable` (
  `id_dia_recuperable` INT NOT NULL AUTO_INCREMENT,
  `dia_recuperable` DATE NOT NULL,
  `id_feriados` INT NOT NULL,
  PRIMARY KEY (`id_dia_recuperable`),
  INDEX `fk_dia_recuperable_n_feriados1_idx` (`id_feriados` ASC),
  CONSTRAINT `fk_dia_recuperable_n_feriados1`
    FOREIGN KEY (`id_feriados`)
    REFERENCES `minerva`.`n_feriados` (`id_feriados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`grupo_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`grupo_empleado` (
  `id_grupo_empleado` INT NOT NULL AUTO_INCREMENT,
  `fecha_ingreso` DATE NOT NULL,
  `id_empleado` INT NOT NULL,
  `id_grupo` INT NOT NULL,
  PRIMARY KEY (`id_grupo_empleado`),
  INDEX `fk_n_dpto_empleado1_idx` (`id_empleado` ASC),
  INDEX `fk_n_grupo_empleado_n_grupo1_idx` (`id_grupo` ASC),
  CONSTRAINT `fk_n_dpto_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `minerva`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_n_grupo_empleado_n_grupo1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `minerva`.`n_grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`c_costo_horas_extras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`c_costo_horas_extras` (
  `id_costo_horas_extras` INT NOT NULL AUTO_INCREMENT,
  `costo` INT NULL,
  PRIMARY KEY (`id_costo_horas_extras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`c_jornada_extra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`c_jornada_extra` (
  `id_jornada_extra` INT NOT NULL AUTO_INCREMENT,
  `extra_ini` TIME NOT NULL,
  `extra_fin` TIME NOT NULL,
  PRIMARY KEY (`id_jornada_extra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`c_hora_extra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`c_hora_extra` (
  `id_hora_extra` INT NOT NULL AUTO_INCREMENT,
  `id_jornada_extra` INT NOT NULL,
  `id_costo_horas_extras` INT NOT NULL,
  PRIMARY KEY (`id_hora_extra`),
  INDEX `fk_c_hora_extra_c_jornada_extra1_idx` (`id_jornada_extra` ASC),
  INDEX `fk_c_hora_extra_c_costo_horas_extras1_idx` (`id_costo_horas_extras` ASC),
  CONSTRAINT `fk_c_hora_extra_c_jornada_extra1`
    FOREIGN KEY (`id_jornada_extra`)
    REFERENCES `minerva`.`c_jornada_extra` (`id_jornada_extra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_c_hora_extra_c_costo_horas_extras1`
    FOREIGN KEY (`id_costo_horas_extras`)
    REFERENCES `minerva`.`c_costo_horas_extras` (`id_costo_horas_extras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`vacaciones_acum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`vacaciones_acum` (
  `id_vacaciones_acum` INT NOT NULL AUTO_INCREMENT,
  `vacaciones_acum` INT NULL,
  `fecha` DATE NULL,
  `id_empleado` INT NOT NULL,
  PRIMARY KEY (`id_vacaciones_acum`),
  INDEX `fk_vacaciones_acum_empleado1_idx` (`id_empleado` ASC),
  CONSTRAINT `fk_vacaciones_acum_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `minerva`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`bono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`bono` (
  `id_bono` INT NOT NULL AUTO_INCREMENT,
  `bono` FLOAT NOT NULL,
  `fecha_pago` DATE NULL,
  `id_empleado` INT NOT NULL,
  PRIMARY KEY (`id_bono`),
  INDEX `fk_bono_empleado1_idx` (`id_empleado` ASC),
  CONSTRAINT `fk_bono_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `minerva`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_causa_ing_sal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_causa_ing_sal` (
  `id_causa_ing_sal` INT NOT NULL AUTO_INCREMENT,
  `causa_ing_sal` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_causa_ing_sal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`ingreso_salida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`ingreso_salida` (
  `id_ingreso_salida` INT NOT NULL AUTO_INCREMENT,
  `fecha_ing_sal` DATE NOT NULL,
  `observacion` VARCHAR(250) NULL,
  `id_empleado` INT NOT NULL,
  `id_causa_ing_sal` INT NOT NULL,
  PRIMARY KEY (`id_ingreso_salida`),
  INDEX `fk_ingreso_salida_empleado1_idx` (`id_empleado` ASC),
  INDEX `fk_ingreso_salida_causa_ing_sal1_idx` (`id_causa_ing_sal` ASC),
  CONSTRAINT `fk_ingreso_salida_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `minerva`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingreso_salida_causa_ing_sal1`
    FOREIGN KEY (`id_causa_ing_sal`)
    REFERENCES `minerva`.`n_causa_ing_sal` (`id_causa_ing_sal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`salario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`salario` (
  `id_salario` INT NOT NULL AUTO_INCREMENT,
  `salario` FLOAT NOT NULL,
  `fecha` DATE NOT NULL,
  `observacion` VARCHAR(250) NULL,
  `id_empleado` INT NOT NULL,
  PRIMARY KEY (`id_salario`),
  INDEX `fk_salario_empleado1_idx` (`id_empleado` ASC),
  CONSTRAINT `fk_salario_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `minerva`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`c_biometrico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`c_biometrico` (
  `id_biometrico` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(5) NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`id_biometrico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`cargo_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`cargo_empleado` (
  `id_cargo_empleado` INT NOT NULL AUTO_INCREMENT,
  `fecha_cargo` DATE NULL,
  `activo` VARCHAR(1) NOT NULL DEFAULT '1',
  `id_empleado` INT NOT NULL,
  `id_cargo` INT NOT NULL,
  PRIMARY KEY (`id_cargo_empleado`),
  INDEX `fk_cargo_empleado_empleado1_idx` (`id_empleado` ASC),
  INDEX `fk_cargo_empleado_n_cargo1_idx` (`id_cargo` ASC),
  CONSTRAINT `fk_cargo_empleado_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `minerva`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cargo_empleado_n_cargo1`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `minerva`.`n_cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`permiso_bloqueado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`permiso_bloqueado` (
  `id_permiso_bloqueado` INT NOT NULL AUTO_INCREMENT,
  `id_accion` INT NOT NULL,
  `id_elemento` INT NOT NULL,
  PRIMARY KEY (`id_permiso_bloqueado`),
  INDEX `fk_permiso_bloqueado_n_accion1_idx` (`id_accion` ASC),
  INDEX `fk_permiso_bloqueado_n_elemento1_idx` (`id_elemento` ASC),
  CONSTRAINT `fk_permiso_bloqueado_n_accion1`
    FOREIGN KEY (`id_accion`)
    REFERENCES `minerva`.`n_accion` (`id_accion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permiso_bloqueado_n_elemento1`
    FOREIGN KEY (`id_elemento`)
    REFERENCES `minerva`.`n_elemento` (`id_elemento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`reemplazo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`reemplazo` (
  `id_reemplazo` INT NOT NULL AUTO_INCREMENT,
  `id_empleado` INT NOT NULL,
  `id_ausencia` INT NOT NULL,
  PRIMARY KEY (`id_reemplazo`),
  INDEX `fk_reemplazo_empleado1_idx` (`id_empleado` ASC),
  INDEX `fk_reemplazo_ausencia1_idx` (`id_ausencia` ASC),
  CONSTRAINT `fk_reemplazo_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `minerva`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reemplazo_ausencia1`
    FOREIGN KEY (`id_ausencia`)
    REFERENCES `minerva`.`ausencia` (`id_ausencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`autoriza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`autoriza` (
  `id_autoriza` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `id_cargo` INT NOT NULL,
  `id_cargo_autoriza` INT NOT NULL,
  PRIMARY KEY (`id_autoriza`),
  INDEX `fk_autoriza_n_cargo1_idx` (`id_cargo` ASC),
  INDEX `fk_autoriza_n_cargo2_idx` (`id_cargo_autoriza` ASC),
  CONSTRAINT `fk_autoriza_n_cargo1`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `minerva`.`n_cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_autoriza_n_cargo2`
    FOREIGN KEY (`id_cargo_autoriza`)
    REFERENCES `minerva`.`n_cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`dia_recuperado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`dia_recuperado` (
  `id_dia_recuperado` INT NOT NULL AUTO_INCREMENT,
  `dia_recuperado` DATE NOT NULL,
  `id_ausencia` INT NOT NULL,
  PRIMARY KEY (`id_dia_recuperado`),
  INDEX `fk_dia_recuperado_ausencia1_idx` (`id_ausencia` ASC),
  CONSTRAINT `fk_dia_recuperado_ausencia1`
    FOREIGN KEY (`id_ausencia`)
    REFERENCES `minerva`.`ausencia` (`id_ausencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`titulo_cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`titulo_cargo` (
  `id_titulo_cargo` INT NOT NULL AUTO_INCREMENT,
  `id_titulo` INT NOT NULL,
  `id_cargo` INT NOT NULL,
  PRIMARY KEY (`id_titulo_cargo`),
  INDEX `fk_titulo_perfil_cargo_n_titulo1_idx` (`id_titulo` ASC),
  INDEX `fk_titulo_perfil_cargo_n_cargo1_idx` (`id_cargo` ASC),
  CONSTRAINT `fk_titulo_perfil_cargo_n_titulo1`
    FOREIGN KEY (`id_titulo`)
    REFERENCES `minerva`.`n_titulo` (`id_titulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_titulo_perfil_cargo_n_cargo1`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `minerva`.`n_cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`usuario_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`usuario_rol` (
  `id_usuario_rol` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario_rol`),
  INDEX `fk_usuario_rol_usuario1_idx` (`id_usuario` ASC),
  INDEX `fk_usuario_rol_n_rol1_idx` (`id_rol` ASC),
  CONSTRAINT `fk_usuario_rol_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `minerva`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_rol_n_rol1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `minerva`.`n_rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_estilo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_estilo` (
  `id_estilo` INT NOT NULL AUTO_INCREMENT,
  `estilo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estilo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`estilo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`estilo_usuario` (
  `id_estilo_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_estilo` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  INDEX `fk_estilo_usuario_n_estilo1_idx` (`id_estilo` ASC),
  INDEX `fk_estilo_usuario_usuario1_idx` (`id_usuario` ASC),
  PRIMARY KEY (`id_estilo_usuario`),
  CONSTRAINT `fk_estilo_usuario_n_estilo1`
    FOREIGN KEY (`id_estilo`)
    REFERENCES `minerva`.`n_estilo` (`id_estilo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estilo_usuario_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `minerva`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`cumplimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`cumplimiento` (
  `id_cumplimiento` INT NOT NULL AUTO_INCREMENT,
  `cumplimiento` VARCHAR(45) NOT NULL,
  `fecha_entrega` DATE NOT NULL,
  `id_compromiso` INT NOT NULL,
  PRIMARY KEY (`id_cumplimiento`),
  INDEX `fk_cumplimiento_compromiso1_idx` (`id_compromiso` ASC),
  CONSTRAINT `fk_cumplimiento_compromiso1`
    FOREIGN KEY (`id_compromiso`)
    REFERENCES `minerva`.`compromiso` (`id_compromiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_punto_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_punto_venta` (
  `id_punto_venta` INT NOT NULL AUTO_INCREMENT,
  `punto_venta` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `permite_credito` VARCHAR(1) NOT NULL COMMENT 'Si paga o no con efectivo:\n1 paga en efectivo\n2 paga a crédito\n3 paga en efectivo o crédito',
  `formato_factura` VARCHAR(10) NULL,
  PRIMARY KEY (`id_punto_venta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`punto_venta_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`punto_venta_usuario` (
  `id_punto_venta_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_punto_venta` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_punto_venta_usuario`),
  INDEX `fk_punto_venta_usuario_n_punto_venta1_idx` (`id_punto_venta` ASC),
  INDEX `fk_punto_venta_usuario_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_punto_venta_usuario_n_punto_venta1`
    FOREIGN KEY (`id_punto_venta`)
    REFERENCES `minerva`.`n_punto_venta` (`id_punto_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_punto_venta_usuario_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `minerva`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_factura` (
  `id_factura` INT NOT NULL AUTO_INCREMENT,
  `no_autorizo` VARCHAR(45) NOT NULL,
  `inicio` INT NOT NULL,
  `fin` INT NOT NULL,
  `fecha_emision` DATE NOT NULL,
  `fecha_vencimiento` DATE NOT NULL,
  `estado` VARCHAR(1) NOT NULL,
  `id_punto_venta` INT NOT NULL,
  PRIMARY KEY (`id_factura`),
  INDEX `fk_n_factura_n_punto_venta1_idx` (`id_punto_venta` ASC),
  CONSTRAINT `fk_n_factura_n_punto_venta1`
    FOREIGN KEY (`id_punto_venta`)
    REFERENCES `minerva`.`n_punto_venta` (`id_punto_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `permite_credito` VARCHAR(1) NOT NULL,
  `factura_nombres` VARCHAR(150) NOT NULL,
  `factura_apellidos` VARCHAR(150) NOT NULL,
  `factura_cedula` VARCHAR(25) NOT NULL,
  `factura_direccion` VARCHAR(200) NOT NULL,
  `factura_telefono` VARCHAR(45) NOT NULL,
  `id_persona` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_persona1_idx` (`id_persona` ASC),
  CONSTRAINT `fk_cliente_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `minerva`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_tarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_tarjeta` (
  `id_tarjeta` INT NOT NULL AUTO_INCREMENT,
  `cod_tarjeta` VARCHAR(45) NOT NULL,
  `cod_barra` VARCHAR(45) NOT NULL,
  `fecha_activacion` DATE NOT NULL,
  `activa` VARCHAR(1) NOT NULL,
  `precio` FLOAT NOT NULL DEFAULT 0,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_tarjeta`),
  INDEX `fk_n_tarjeta_cliente1_idx` (`id_cliente` ASC),
  CONSTRAINT `fk_n_tarjeta_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `minerva`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_forma_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_forma_pago` (
  `id_forma_pago` INT NOT NULL AUTO_INCREMENT,
  `forma_pago` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_forma_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`saldo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`saldo` (
  `id_saldo` INT NOT NULL AUTO_INCREMENT,
  `saldo` FLOAT NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `id_forma_pago` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_punto_venta` INT NOT NULL,
  PRIMARY KEY (`id_saldo`),
  INDEX `fk_saldo_n_forma_pago1_idx` (`id_forma_pago` ASC),
  INDEX `fk_saldo_cliente1_idx` (`id_cliente` ASC),
  INDEX `fk_saldo_n_punto_venta1_idx` (`id_punto_venta` ASC),
  CONSTRAINT `fk_saldo_n_forma_pago1`
    FOREIGN KEY (`id_forma_pago`)
    REFERENCES `minerva`.`n_forma_pago` (`id_forma_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_saldo_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `minerva`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_saldo_n_punto_venta1`
    FOREIGN KEY (`id_punto_venta`)
    REFERENCES `minerva`.`n_punto_venta` (`id_punto_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `cod_producto` VARCHAR(45) NOT NULL,
  `producto` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`producto_precio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`producto_precio` (
  `id_producto_precio` INT NOT NULL AUTO_INCREMENT,
  `precio` FLOAT NOT NULL,
  `fecha` DATE NOT NULL,
  `graba_iva` VARCHAR(1) NOT NULL,
  `activo` VARCHAR(1) NOT NULL,
  `id_producto` INT NOT NULL,
  `id_punto_venta` INT NOT NULL,
  PRIMARY KEY (`id_producto_precio`),
  INDEX `fk_producto_precio_n_producto1_idx` (`id_producto` ASC),
  INDEX `fk_producto_precio_n_punto_venta1_idx` (`id_punto_venta` ASC),
  CONSTRAINT `fk_producto_precio_n_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `minerva`.`n_producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_precio_n_punto_venta1`
    FOREIGN KEY (`id_punto_venta`)
    REFERENCES `minerva`.`n_punto_venta` (`id_punto_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`venta` (
  `id_venta` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `fecha_venta` DATETIME NOT NULL,
  `no_factura` VARCHAR(45) NOT NULL,
  `anulada` VARCHAR(1) NOT NULL,
  `id_factura` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_producto_precio` INT NOT NULL,
  PRIMARY KEY (`id_venta`),
  INDEX `fk_venta_n_factura1_idx` (`id_factura` ASC),
  INDEX `fk_venta_cliente1_idx` (`id_cliente` ASC),
  INDEX `fk_venta_producto_precio1_idx` (`id_producto_precio` ASC),
  CONSTRAINT `fk_venta_n_factura1`
    FOREIGN KEY (`id_factura`)
    REFERENCES `minerva`.`n_factura` (`id_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `minerva`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_producto_precio1`
    FOREIGN KEY (`id_producto_precio`)
    REFERENCES `minerva`.`producto_precio` (`id_producto_precio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_subproducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_subproducto` (
  `id_subproducto` INT NOT NULL AUTO_INCREMENT,
  `cod_subproducto` VARCHAR(45) NOT NULL,
  `subproducto` VARCHAR(150) NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  PRIMARY KEY (`id_subproducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_unidad_medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_unidad_medida` (
  `id_unidad_medida` INT NOT NULL AUTO_INCREMENT,
  `unidad_medida` VARCHAR(45) NOT NULL COMMENT 'La unidad de medida hay que forzarla en la aplicación para que sea la misma en la COMPRA, RECETA Y MERMA',
  PRIMARY KEY (`id_unidad_medida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`receta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`receta` (
  `id_receta` INT NOT NULL AUTO_INCREMENT,
  `cantidad_sub` FLOAT NOT NULL,
  `id_subproducto` INT NOT NULL,
  `id_unidad_medida` INT NOT NULL,
  `id_producto` INT NOT NULL,
  PRIMARY KEY (`id_receta`),
  INDEX `fk_receta_n_subproducto1_idx` (`id_subproducto` ASC),
  INDEX `fk_receta_n_unidad_medida1_idx` (`id_unidad_medida` ASC),
  INDEX `fk_receta_n_producto1_idx` (`id_producto` ASC),
  CONSTRAINT `fk_receta_n_subproducto1`
    FOREIGN KEY (`id_subproducto`)
    REFERENCES `minerva`.`n_subproducto` (`id_subproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receta_n_unidad_medida1`
    FOREIGN KEY (`id_unidad_medida`)
    REFERENCES `minerva`.`n_unidad_medida` (`id_unidad_medida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receta_n_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `minerva`.`n_producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`referencia` (
  `id_referencia` INT NOT NULL AUTO_INCREMENT,
  `referencia` VARCHAR(300) NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_punto_venta` INT NOT NULL,
  PRIMARY KEY (`id_referencia`),
  INDEX `fk_referencia_cliente1_idx` (`id_cliente` ASC),
  INDEX `fk_referencia_n_punto_venta1_idx` (`id_punto_venta` ASC),
  CONSTRAINT `fk_referencia_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `minerva`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_referencia_n_punto_venta1`
    FOREIGN KEY (`id_punto_venta`)
    REFERENCES `minerva`.`n_punto_venta` (`id_punto_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `desc_prov` VARCHAR(250) NOT NULL,
  `ruc` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`compra` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `costo` FLOAT NOT NULL,
  `cantidad` INT NOT NULL,
  `observacion` VARCHAR(250) NULL,
  `id_subproducto` INT NOT NULL,
  `id_unidad_medida` INT NOT NULL,
  `id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `fk_compra_n_subproducto1_idx` (`id_subproducto` ASC),
  INDEX `fk_compra_n_unidad_medida1_idx` (`id_unidad_medida` ASC),
  INDEX `fk_compra_n_proveedor1_idx` (`id_proveedor` ASC),
  CONSTRAINT `fk_compra_n_subproducto1`
    FOREIGN KEY (`id_subproducto`)
    REFERENCES `minerva`.`n_subproducto` (`id_subproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_n_unidad_medida1`
    FOREIGN KEY (`id_unidad_medida`)
    REFERENCES `minerva`.`n_unidad_medida` (`id_unidad_medida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_n_proveedor1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `minerva`.`n_proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`merma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`merma` (
  `id_merma` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `cantidad` INT NOT NULL,
  `causa` VARCHAR(150) NULL,
  `id_subproducto` INT NOT NULL,
  `id_unidad_medida` INT NOT NULL,
  PRIMARY KEY (`id_merma`),
  INDEX `fk_merma_n_unidad_medida1_idx` (`id_unidad_medida` ASC),
  INDEX `fk_merma_n_subproducto1_idx` (`id_subproducto` ASC),
  CONSTRAINT `fk_merma_n_unidad_medida1`
    FOREIGN KEY (`id_unidad_medida`)
    REFERENCES `minerva`.`n_unidad_medida` (`id_unidad_medida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_merma_n_subproducto1`
    FOREIGN KEY (`id_subproducto`)
    REFERENCES `minerva`.`n_subproducto` (`id_subproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`estudiante` (
  `id_estudiante` INT NOT NULL AUTO_INCREMENT,
  `id_persona` INT NOT NULL,
  `lugar_nacimiento` VARCHAR(45) NULL,
  `tipo_vivienda` VARCHAR(1) NOT NULL,
  `colegio_proviene` VARCHAR(45) NULL,
  `razones_cambio` VARCHAR(250) NULL,
  `tratamiento_profesional` VARCHAR(250) NULL,
  `observaciones` VARCHAR(250) NULL,
  PRIMARY KEY (`id_estudiante`),
  INDEX `fk_estudiante_persona1_idx` (`id_persona` ASC),
  CONSTRAINT `fk_estudiante_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `minerva`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_parentesco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_parentesco` (
  `id_parentesco` INT NOT NULL AUTO_INCREMENT,
  `parentesco` VARCHAR(45) NULL,
  PRIMARY KEY (`id_parentesco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`familiar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`familiar` (
  `id_familiar` INT NOT NULL AUTO_INCREMENT,
  `id_persona` INT NOT NULL,
  `lugar_nacimiento` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  `profesion` VARCHAR(50) NULL,
  `lugar_trabajo` VARCHAR(50) NULL,
  `dir_trabajo` VARCHAR(200) NULL,
  `cargo` VARCHAR(45) NULL,
  `tel_trabajo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_familiar`),
  INDEX `fk_familiar_persona1_idx` (`id_persona` ASC),
  CONSTRAINT `fk_familiar_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `minerva`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`familiar_estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`familiar_estudiante` (
  `id_familiar_estudiante` INT NOT NULL AUTO_INCREMENT,
  `id_familiar` INT NOT NULL,
  `id_estudiante` INT NOT NULL,
  `id_parentesco` INT NOT NULL,
  `representante_legal` VARCHAR(1) NOT NULL,
  `representante_aca` VARCHAR(1) NOT NULL,
  `representante_eco` VARCHAR(1) NOT NULL,
  `convive` VARCHAR(1) NOT NULL,
  `puede_retirar` VARCHAR(1) NOT NULL,
  `contacto_emergencia` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id_familiar_estudiante`),
  INDEX `fk_familiar_estudiante_familiar1_idx` (`id_familiar` ASC),
  INDEX `fk_familiar_estudiante_estudiante1_idx` (`id_estudiante` ASC),
  INDEX `fk_familiar_estudiante_n_parentesco1_idx` (`id_parentesco` ASC),
  CONSTRAINT `fk_familiar_estudiante_familiar1`
    FOREIGN KEY (`id_familiar`)
    REFERENCES `minerva`.`familiar` (`id_familiar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_familiar_estudiante_estudiante1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `minerva`.`estudiante` (`id_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_familiar_estudiante_n_parentesco1`
    FOREIGN KEY (`id_parentesco`)
    REFERENCES `minerva`.`n_parentesco` (`id_parentesco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_periodo_academico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_periodo_academico` (
  `id_periodo_academico` INT NOT NULL AUTO_INCREMENT,
  `fecha_ini` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `activo` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id_periodo_academico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_grupo_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_grupo_cliente` (
  `id_grupo_cliente` INT NOT NULL AUTO_INCREMENT,
  `grupo_cliente` VARCHAR(45) NOT NULL,
  `id_punto_venta` INT NOT NULL,
  PRIMARY KEY (`id_grupo_cliente`),
  INDEX `fk_n_grupo_persona_n_punto_venta1_idx` (`id_punto_venta` ASC),
  CONSTRAINT `fk_n_grupo_persona_n_punto_venta1`
    FOREIGN KEY (`id_punto_venta`)
    REFERENCES `minerva`.`n_punto_venta` (`id_punto_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`grupos_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`grupos_clientes` (
  `id_grupos_clientes` INT NOT NULL AUTO_INCREMENT,
  `id_grupo_cliente` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `activo` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id_grupos_clientes`),
  INDEX `fk_grupos_empleados_grupo_empleado1_idx` (`id_grupo_cliente` ASC),
  INDEX `fk_grupos_personas_cliente1_idx` (`id_cliente` ASC),
  CONSTRAINT `fk_grupos_empleados_grupo_empleado1`
    FOREIGN KEY (`id_grupo_cliente`)
    REFERENCES `minerva`.`n_grupo_cliente` (`id_grupo_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupos_personas_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `minerva`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`preventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`preventa` (
  `id_preventa` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `id_grupo_cliente` INT NOT NULL,
  PRIMARY KEY (`id_preventa`),
  INDEX `fk_preventa_n_producto1_idx` (`id_producto` ASC),
  INDEX `fk_preventa_n_grupo_persona1_idx` (`id_grupo_cliente` ASC),
  CONSTRAINT `fk_preventa_n_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `minerva`.`n_producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preventa_n_grupo_persona1`
    FOREIGN KEY (`id_grupo_cliente`)
    REFERENCES `minerva`.`n_grupo_cliente` (`id_grupo_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_paralelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_paralelo` (
  `id_paralelo` INT NOT NULL AUTO_INCREMENT,
  `paralelo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_paralelo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`n_grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`n_grado` (
  `id_grado` INT NOT NULL AUTO_INCREMENT,
  `grado` VARCHAR(45) NOT NULL,
  `id_proximo_grado` INT NULL,
  `ultimo_grado` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id_grado`),
  INDEX `fk_n_grado_n_grado1_idx` (`id_proximo_grado` ASC),
  CONSTRAINT `fk_n_grado_n_grado1`
    FOREIGN KEY (`id_proximo_grado`)
    REFERENCES `minerva`.`n_grado` (`id_grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`curso_grado_paralelo_est`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`curso_grado_paralelo_est` (
  `id_curso_grado_paralelo_est` INT NOT NULL AUTO_INCREMENT,
  `id_grado` INT NOT NULL,
  `id_paralelo` INT NOT NULL,
  `id_estudiante` INT NOT NULL,
  `id_periodo_academico` INT NOT NULL,
  `fecha_admision` DATE NOT NULL,
  `fecha_desadmision` DATE NULL,
  `cumplido` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id_curso_grado_paralelo_est`),
  INDEX `fk_curso_grado_paralelo_est_n_grado1_idx` (`id_grado` ASC),
  INDEX `fk_curso_grado_paralelo_est_n_paralelo1_idx` (`id_paralelo` ASC),
  INDEX `fk_curso_grado_paralelo_est_estudiante1_idx` (`id_estudiante` ASC),
  INDEX `fk_curso_grado_paralelo_est_n_periodo_academico1_idx` (`id_periodo_academico` ASC),
  CONSTRAINT `fk_curso_grado_paralelo_est_n_grado1`
    FOREIGN KEY (`id_grado`)
    REFERENCES `minerva`.`n_grado` (`id_grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_grado_paralelo_est_n_paralelo1`
    FOREIGN KEY (`id_paralelo`)
    REFERENCES `minerva`.`n_paralelo` (`id_paralelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_grado_paralelo_est_estudiante1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `minerva`.`estudiante` (`id_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_grado_paralelo_est_n_periodo_academico1`
    FOREIGN KEY (`id_periodo_academico`)
    REFERENCES `minerva`.`n_periodo_academico` (`id_periodo_academico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`clinica_preferencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`clinica_preferencia` (
  `id_clinica_preferencia` INT NOT NULL AUTO_INCREMENT,
  `clinica_preferencia` VARCHAR(100) NOT NULL,
  `indicaciones` VARCHAR(250) NULL,
  `id_estudiante` INT NOT NULL,
  PRIMARY KEY (`id_clinica_preferencia`),
  INDEX `fk_clinica_preferencia_estudiante1_idx` (`id_estudiante` ASC),
  CONSTRAINT `fk_clinica_preferencia_estudiante1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `minerva`.`estudiante` (`id_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minerva`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minerva`.`matricula` (
  `id_matricula` INT NOT NULL AUTO_INCREMENT,
  `codigo_matricula` VARCHAR(45) NOT NULL,
  `fecha_matricula` DATE NOT NULL,
  `fecha_desmatricula` DATE NULL,
  `id_curso_grado_paralelo_est` INT NOT NULL,
  PRIMARY KEY (`id_matricula`),
  INDEX `fk_matricula_curso_grado_paralelo_est1_idx` (`id_curso_grado_paralelo_est` ASC),
  CONSTRAINT `fk_matricula_curso_grado_paralelo_est1`
    FOREIGN KEY (`id_curso_grado_paralelo_est`)
    REFERENCES `minerva`.`curso_grado_paralelo_est` (`id_curso_grado_paralelo_est`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `minerva`;

DELIMITER $$
USE `minerva`$$
$$

USE `minerva`$$
$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
